spring:
  application:
    name: service-api-gateway

zuul:
  ignoredServices: '*'
  routes:
    orderService:
      path: /order/**
      serviceId: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true