server:
  host: "0"

elasticsearch:
  url: http://elasticsearch:9200
  username: elastic
  password: changeme

xpack:
  monitoring:
    ui:
      container:
          elasticsearch:
            enabled: true