version: '3'
services:
  service-discovery:
    image: io.github.devbhuwan/micro-service-nutshell-service-discovery:1.0-SNAPSHOT
    environment:
      - EUREKA_HOSTNAME=localhost
      - PORT=8761
    ports:
      - 8761
  configuration:
    image: io.github.devbhuwan/micro-service-nutshell-configuration:1.0-SNAPSHOT
    environment:
      - EUREKA_URI=http://service-discovery:8761/eureka
    links:
      - service-discovery
  order-service:
    image: io.github.devbhuwan/micro-service-nutshell-order-service-runner:1.0-SNAPSHOT
    environment:
      - CONFIGURATION_URI=http://configuration:8888
      - EUREKA_URI=http://service-discovery:8761/eureka
      - PORT=8080
    links:
      - configuration
      - service-discovery
    depends_on:
      - configuration
      - service-discovery
  service-api-gateway:
    image: io.github.devbhuwan/micro-service-nutshell-service-api-gateway:1.0-SNAPSHOT
    environment:
      - CONFIGURATION_URI=http://configuration:8888
      - EUREKA_URI=http://service-discovery:8761/eureka
      - PORT=8484
    links:
      - configuration
      - service-discovery
    depends_on:
      - configuration
      - service-discovery