spring:
  application:
    name: order-service
  jersey:
    application-path: /api

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true