spring:
  application:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://oms-service-discovery.herokuapp.com/eureka}
  instance:
    preferIpAddress: true