version: '3'
services:
  service-discovery:
    image: io.github.devbhuwan/micro-service-nutshell-service-discovery:1.0-SNAPSHOT
    environment:
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}
      - PORT=8761
    ports:
      - 8761:8761
  configuration:
    image: io.github.devbhuwan/micro-service-nutshell-configuration:1.0-SNAPSHOT
    environment:
      - EUREKA_URI=http://service-discovery:8761/eureka
      - PORT=8888
    ports:
      - 8888:8888
    links:
      - service-discovery