version: '3'
services:
  registry:
    image: io.github.devbhuwan/oms-service-registry:1.0-SNAPSHOT
    ports:
      - 8761:8761
  config:
    image: io.github.devbhuwan/oms-configuration:1.0-SNAPSHOT
    environment:
      - EUREKA_URI=${EUREKA_URI}
    links:
      - registry
  gateway:
    image: io.github.devbhuwan/oms-service-api-gateway:1.0-SNAPSHOT
    environment:
      - EUREKA_URI=${EUREKA_URI}
      - CONFIGURATION_URI=${CONFIGURATION_URI}
    ports:
      - 8484:8484
    links:
      - registry
  auth-server:
    image: io.github.devbhuwan/oms-service-auth-server:1.0-SNAPSHOT
    environment:
      - EUREKA_URI=${EUREKA_URI}
      - CONFIGURATION_URI=${CONFIGURATION_URI}
    links:
      - registry
  order-service:
    image: io.github.devbhuwan/oms-order-service:1.0-SNAPSHOT
    environment:
      - EUREKA_URI=${EUREKA_URI}
      - CONFIGURATION_URI=${CONFIGURATION_URI}
      - LOGSTASH = ${LOGSTASH}
    links:
      - registry
      - logstash