version: '3'
services:
  base:
    image: hello-world
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    volumes:
      - ./monitoring/jolokia-jvm-1.3.6-agent.jar:/jolokia-jvm-1.3.6-agent.jar:ro

  discovery:
    image: io.github.devbhuwan/oms-service-discovery:1.0-SNAPSHOT
    command: java -javaagent:/jolokia-jvm-1.3.6-agent.jar=port=7777,host=0.0.0.0,discoveryEnabled=false -Xmx512m -jar /app.jar
    ports:
      - "8761:8761"
    links:
      - base
    labels:
      io.github.devbhuwan.service: "eureka"
      io.github.devbhuwan.service.type: "utils"
    volumes:
      - ./monitoring/jolokia-jvm-1.3.6-agent.jar:/jolokia-jvm-1.3.6-agent.jar:ro

# Logging components

  elasticsearch:
    image: elasticsearch:5.2-alpine
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    labels:
      io.github.devbhuwan.service: "elasticsearch"
      io.github.devbhuwan.service.type: "logging"

  logstash:
    image: logstash:5.2-alpine
    command: logstash -f /logging/logstash.conf
    # uncomment to enable output of all incoming messages to stdout of logstash container
    # command: logstash -e 'input { gelf { } } filter { } output { elasticsearch { hosts => "elasticsearch:9200" } stdout { codec => rubydebug } }'

    ports:
      - "12201:12201/udp"
      - "4260:4260/tcp"
    volumes:
      - ./logging/:/logging/
    depends_on:
      - elasticsearch
    labels:
      io.github.devbhuwan.service: "logstash"
      io.github.devbhuwan.service.type: "logging"

  kibana:
    image: kibana:5.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    labels:
      io.github.devbhuwan.service: "kibana"
      io.github.devbhuwan.service.type: "logging"

networks:
  default:

volumes:
  vol-core-db: