server:
  port: ${PORT:8484}

spring:
  application:
      name: service-api-gateway
  cloud:
    config:
      enabled: true
      uri: ${CONFIGURATION_URI:http://localhost:8888}
      fail-fast: true
      retry:
        initialInterval: 2000
        multiplier: 1.2
        maxInterval: 5000
        maxAttempts: 10

zuul:
  ignoredServices: '*'
  routes:
    orderService:
      path: /order/**
      serviceId: order-service
    test:
      path: /test/**
      url: http://localhost:9092/api/

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true