spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.h2.Driver

server:
  port: ${PORT:8484}
  context-path: /v1-order-service

ignite:
  cfgPath: classpath:config/ignite/order-ignite-cfg.xml