spring:
  application:
    name: order-service

server:
  port: ${PORT:8484}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true