version: '3'
services:
  order-service:
    image: io.github.devbhuwan/oms-order-service-runner:1.0-SNAPSHOT
    environment:
      - CONFIGURATION_URI=${CONFIGURATION_URI}
      - EUREKA_URI=${EUREKA_URI}
      - PORT=8080
    ports:
      - 8080:8080
#  service-api-gateway:
#    image: io.github.devbhuwan/oms-service-api-gateway:1.0-SNAPSHOT
#    environment:
#      - CONFIGURATION_URI=${CONFIGURATION_URI}
#      - EUREKA_URI=${EUREKA_URI}
#      - PORT=8484
#    ports:
#      - 8484:8484